### ISSUE TITLE
Get feedback on comparison with sphinx-multiversion

### ISSUE THREAD

**Issue by goerz** [goerz/docs_versions_menu#22]
The release candidate for `v0.5.0` (first release of the renamed `docs-versions-menu`) [contains a comparison with the sphinx-multiversion package](https://goerz.github.io/docs_versions_menu/v0.5.0-rc1/related_software.html#comparison-with-sphinx-multiversion)

It would be nice to have someone with real first-hand knowledge of `sphinx-multiversion` look this over.

@Holzhaus If you have any thoughts on the comparison, let me know. I'd want to avoid any misrepresentation of your (very nice!) project based on something I might have misunderstood from its documentation. Conversely, if there's anything I can clarify about `docs-versions-menu`, I'll be happy to answer questions.

@CAM-Gerlach If you have any feedback on the documentation based on your experience with using `sphinx-multiversion`, feel free to chime in (you might also be interested in #21)

**Comment by CAM-Gerlach** [comment]
Sorry, realized I never submitted this yesterday...

@goerz At least from my personal perspective as a regular `Sphinx-Multiversion` user and theme integrator (with @dalthviz ), I think what you wrote does a great job capturing the benefits, drawbacks and use-cases of both from a nuetral point of view, and it was a great balance of detail and accessibility. I'm far from an expert like @Holzhaus or others, but at least as far as my experience is concerned, I don't think there is anything I have to add beyond your excellent summary.

**Comment by Holzhaus** [comment]
I think you pointed out the advantages and disadvantages of sphinx-multiversion well.

**Comment by goerz** [comment]
Thanks guys! I appreciate the feedback!
