### ISSUE TITLE
LegacyVersion has been removed from packaging.version

### ISSUE THREAD

**Issue by awoimbee** [goerz/docs_versions_menu#27]
* docs_versions_menu version: latest (0.5.0+dev)
* Python version: 3.10
* Operating System: linux

### Description

`LegacyVersion` was removed. Trying to use it raises an error:
```
Extension error:
Could not import extension docs_versions_menu (exception: cannot import name 'LegacyVersion' from 'packaging.version' (/[...]/site-packages/packaging/version.py))
ERROR: InvocationError for command /[...]/bin/sphinx-build -M html . _build (exited with code 2)
```

### What I Did

https://github.com/awoimbee/docs_versions_menu/commit/d6063fd0ccf26bfce6a9fcf07c9251863d16ec3a

**Comment by goerz** [comment]
The `packaging` library removed `LegacyVersion` in their release 22.0.

I'm going to pin `packaging < 22.0` until I can work around this.
