### ISSUE TITLE
Deprecate config-file

### ISSUE THREAD

**Issue by goerz** [goerz/docs_versions_menu#9]
Following up on #6 and #7 and the [introduction of environment variables](https://github.com/goerz/doctr_versions_menu/issues/6#issuecomment-667788882) to configure the `doctr-versions-menu`, I feel somewhat strongly inclined to deprecate and eventually entirely remove support for the [config file](https://goerz.github.io/doctr_versions_menu/v0.3.0/command.html#doctr-versions-menu-conf-configuration-file) in future versions, and to have [environment variables](https://goerz.github.io/doctr_versions_menu/v0.3.0/command.html#doctr-versions-menu-environment-variables) as the *only* mechanism for configuration (apart from explicit command line flags).

This would help with keeping all configuration on the source branch as @ZryletTC pointed out in #6, something that I strongly agree with, as a design goal. It would also simplify the documentation (["only one way to do it"](https://wiki.python.org/moin/TOOWTDI)) and eliminate [quite a bit of unnecessary code](https://github.com/goerz/doctr_versions_menu/blob/v0.3.0/src/doctr_versions_menu/click_config_file.py) (I'm also actually not a huge fan of the [configobj-unrepr](https://configobj.readthedocs.io/en/latest/configobj.html#unrepr-mode) syntax used in the config).

@ZryletTC and @hhslepicka: What do you think?

**Comment by ZryletTC** [comment]
That sounds like a good plan. As long as the environment variables stay specific to doctr_versions, there shouldn't be any conflicts. And as long as the one way is widely usable (which environment variables on Travis are, "one way to do it" is great :)
